version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn jewelry.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  # remove this in production
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - celery
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A jewelry worker --loglevel=info
    volumes:
      - .:/app  # remove this in production
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A jewelry beat --loglevel=info
    volumes:
      - .:/app  # remove this in production
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
