version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      gunicorn jewelry.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - celery
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      celery -A jewelry worker --loglevel=info
    volumes:
      - type: bind
        source: .
        target: /app
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      celery -A jewelry beat --loglevel=info
    volumes:
      - type: bind
        source: .
        target: /app
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    restart: always
