name: Deploy on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install MySQL build dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config default-libmysqlclient-dev
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_IMAGE: ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          ALT_IMAGE: pritvirajmagar/tejas-repo:latest
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest $DOCKERHUB_IMAGE
          docker tag myapp:latest $ALT_IMAGE
          docker push $DOCKERHUB_IMAGE
          docker push $ALT_IMAGE

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/myapp:latest
